steps:
- name: node:10.0.0
  entrypoint: npm
  args: ["install"]

- name: node:10.0.0
  entrypoint: npm
  args: ["cache", "verify"]

- name: node:10.0.0
  entrypoint: npm
  args: ["run", "build"]

- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]

timeout: "1600s"
